### ISSUE TITLE
[3Di]: "Manhole surface level is below bottom level" error not catched by schematisationchecker

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#10]
- [x] https://github.com/nens/threedi-modelchecker/issues/123

### Contact Details

Rebecca

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=f33d99d5-2988-4d29-a4c9-7264e251f5c6

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Rebecca's original message: 

ik heb weer een error gevonden in INPY die er niet uit wordt gehaald door de schematisatiechecker.

Het gaat om de volgende error

** ERROR : Manhole surface level is below bottom level, Calculation node = 3763, bottom level = -6.0000, drain level = -9999.0000

Belangrijk hierbij is dat ik niet 1 manhole had waarvan daadwerkelijk de drain level lager was dan de bottom level (in de tabel). Het kwam daarom ook niet uit de schematisatiechecker (want als je dat wel hebt, komt dat er wel uit). Wat ik wel had is een losliggende connection node waar wel een manhole op zat, maar verder geen kunstwerken of leidingen. Denk dat het een goeie toevoeging is om ook te checken op connection nodes waar wel een manhole op zit, maar verder niks.

### How to Reproduce?

zutphen-zutphen_default-29-a9739bf1daaaf596b6c4ef52d8680e81ba80982e

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Melding via Jonas ontvangen en besproken tijdens het servicedesk 3Di overleg

**Comment by lisannewapstra** [comment]
done
