### ISSUE TITLE
[3Di]: QPE forecast Rain does not work

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#102]
- [x] https://github.com/nens/threedi-live-site/issues/1064

### Contact Details

Wayne

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=a19ffe3f-ccb6-4e53-bcce-060390c62a9c

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Livesite

### What happened?

"Failed to send request" when trying to create a QPE Forecast

### How to Reproduce?

Example of model when it occurs (occurs in more models thought): 46594

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/188138636-83a3dccf-5a2a-4fb6-b0bf-30e6a8acfec5.png)

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
done
