### ISSUE TITLE
[3Di]: Simulation length does not mention days and goes from 23h to 0h.

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#104]
- [x] https://github.com/nens/nens-frontends/issues/223

### Contact Details

Leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7d867e51-f987-4383-98c1-4aec98789774

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

On https://management.3di.live/simulations, the simulation length is listed. But after 24h it resets to 0h, withouth mentioning the days. Leendert would like to see days as well.

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/188139730-6d55980c-a5fb-4818-9a87-c8e65a1408bd.png)

Here it seems like the 1st listed simulation has only run for 3h 42m, but in reality it is 1d3h42m.

### Additional info

Anything else you would like to share?

**Comment by Patrick-Nijman** [comment]
Staat nu op staging, gaat met de volgende productie release mee
