### ISSUE TITLE
[3Di]: sending rain request failed with request Object error (productie)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#105]
### Incident Type

Error

### 3Di component

Livesite

### What happened?

I opened the 3di_logo_radar_data_and_nodata model (nr 21)
I tried to radar rain
From 13/10/2013 9:00 AM
To 13/10/2013 11:00 PM
I got a message below adding the rain that the communication with the server failed.

### How to Reproduce?

I opened the 3di_logo_radar_data_and_nodata model (nr 21)
I tried to radar rain
From 13/10/2013 9:00 AM
To 13/10/2013 11:00 PM
I got a message below adding the rain that the communication with the server failed.

### What did you expect and what was the actual result?

I expected that I would be able to add the rain to the model.

### Add screenshots, video's etc

![20220906 - 3di live - cannot radar rain](https://user-images.githubusercontent.com/13179397/188683362-59efccd5-952a-4b69-ad3d-dc12bb6fb605.png)
Some of the zonal statistics request give 400 errors
Could this have something to do with it?
![20220906 - 3di live - cannot radar rain -400 error zonal statistic sometimes 200](https://user-images.githubusercontent.com/13179397/188683429-4a93a636-f992-41e1-a4ff-c2160401d702.png)

### Relevant log output

```shell
RainMenuRaster.tsx:193 sending rain request failed with request Objectdata: {referenceUuid: 'd6c2347d-7bd1-4d9d-a1f6-b342c865516f', offset: 0, duration: 50400, units: 'm/s', startDatetime: Sun Oct 13 2013 09:00:00 GMT+0200 (Midden-Europese zomertijd)}simulationPk: "91448"[[Prototype]]: Object error: Responsebody: (...)bodyUsed: falseheaders: Headers[[Prototype]]: Headersappend: ƒ append()delete: ƒ delete()entries: ƒ entries()forEach: ƒ forEach()get: ƒ ()has: ƒ has()keys: ƒ keys()set: ƒ ()values: ƒ values()constructor: ƒ Headers()Symbol(Symbol.iterator): ƒ entries()Symbol(Symbol.toStringTag): "Headers"[[Prototype]]: Objectok: falseredirected: falsestatus: 401statusText: ""type: "cors"url: "https://api.3di.live/v3/simulations/91448/events/rain/rasters/lizard/"[[Prototype]]: ResponsearrayBuffer: ƒ arrayBuffer()blob: ƒ blob()body: (...)bodyUsed: (...)clone: ƒ clone()formData: ƒ formData()headers: (...)json: ƒ json()ok: (...)redirected: (...)status: (...)statusText: (...)text: ƒ text()type: (...)url: (...)constructor: ƒ Response()Symbol(Symbol.toStringTag): "Response"get body: ƒ body()get bodyUsed: ƒ bodyUsed()get headers: ƒ headers()get ok: ƒ ok()get redirected: ƒ redirected()get status: ƒ status()get statusText: ƒ statusText()get type: ƒ type()get url: ƒ url()[[Prototype]]: Object
(anonymous) @ RainMenuRaster.tsx:193
useLizardAggregates.ts:83          GET https://demo.lizard.net/api/v4/rasters/d6c2347d-7bd1-4d9d-a1f6-b342c865516f/zonal/?zonal_statistic=mean&temporal_statistic=sum&frequency=5min&geom=POLYGON((+4.666201413899661+52.14488033904936,+4.669672737676851+52.14488033904936,+4.669672737676851+52.14705868436088,+4.666201413899661+52.14705868436088,+4.666201413899661+52.14488033904936))&start=2013-10-13T07:00:00Z&stop=2013-10-13T21:00:00Z 404
(anonymous) @ useLizardAggregates.ts:83
fetchFn @ index.js:1035
e @ index.js:605
Z @ index.js:651
value @ index.js:1090
value @ index.js:2299
value @ index.js:2287
value @ index.js:2270
value @ index.js:886
(anonymous) @ index.js:1349
(anonymous) @ index.js:1348
batch @ index.js:686
value @ index.js:1347
(anonymous) @ index.js:1833
(anonymous) @ index.js:413
value @ index.js:412
(anonymous) @ index.js:398
e @ index.js:360

useLizardAggregates.ts:83 
 GET https://demo.lizard.net/api/v4/rasters/d6c2347d-7bd1-4d9d-a1f6-b342c865516f…1+52.14488033904936))&start=2013-10-13T07:00:00Z&stop=2013-10-13T21:00:00Z 404
(anonymous)	@	useLizardAggregates.ts:83
fetchFn	@	index.js:1035
e	@	index.js:605
Z	@	index.js:651
value	@	index.js:1090
value	@	index.js:2299
value	@	index.js:2287
value	@	index.js:2270
value	@	index.js:886
(anonymous)	@	index.js:1349
(anonymous)	@	index.js:1348
batch	@	index.js:686
value	@	index.js:1347
(anonymous)	@	index.js:1833
(anonymous)	@	index.js:413
value	@	index.js:412
(anonymous)	@	index.js:398
e	@	index.js:360
useLizardAggregates.ts:83 
 GET https://demo.lizard.net/api/v4/rasters/d6c2347d-7bd1-4d9d-a1f6-b342c865516f…1+52.14488033904936))&start=2013-10-13T07:00:00Z&stop=2013-10-13T21:00:00Z 404
(anonymous)	@	useLizardAggregates.ts:83
fetchFn	@	index.js:1035
e	@	index.js:605
Z	@	index.js:651
value	@	index.js:1090
value	@	index.js:2299
value	@	index.js:2287
value	@	index.js:2270
value	@	index.js:886
(anonymous)	@	index.js:1349
(anonymous)	@	index.js:1348
batch	@	index.js:686
value	@	index.js:1347
(anonymous)	@	index.js:1833
(anonymous)	@	index.js:413
value	@	index.js:412
(anonymous)	@	index.js:398
e	@	index.js:360
```

### Additional info

Null values when following the api calls to zonal statistics:
(final part of log output)
https://demo.lizard.net/api/v4/rasters/d6c2347d-7bd1-4d9d-a1f6-b342c865516f/zonal/?zonal_statistic=mean&temporal_statistic=sum&frequency=5min&geom=POLYGON((+4.666201413899661+52.14488033904936,+4.669672737676851+52.14488033904936,+4.669672737676851+52.14705868436088,+4.666201413899661+52.14705868436088,+4.666201413899661+52.14488033904936))&start=2013-10-13T07:00:00Z&stop=2013-10-13T21:00:00Z

A little bit earlier today I tested v2_bergermeer_with_grndwtr  #111 with radar rain 28-07-2014 8:00 tot 15:00
and uniform_grid_20m_grid #20 with radar rain 28 juli 2014 start at 06:00 till 18:00
That went well. (water pun not intended)

Good luck! :)

**Comment by GeOdin** [comment]
It works again. :)

Maybe there was a restart of a server?
Not sure if I should close this ticket or it could happen again.

For now I will keep this ticket open, just without high priority.

**Comment by Patrick-Nijman** [comment]
Can't reproduce. This seems like a glitch related to maintenance
