### ISSUE TITLE
[3Di]: Obstacle in livesite als 1D element

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/servicedesk-issue-only#107]
- [x] https://github.com/nens/threedi-api/issues/1747

### Contact Details

Patrick

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/mango/window/0?t=1663055609480

### Incident Type

Feature Request

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

API - v3 (Default)

### What happened?

De adviseur zou graag ook de obstacle als lijn-element terugzien in de livesite, om beter inzichtelijk te krijgen wat er gebeurd in het watersysteem.

JSON moet beschikbaar worden van de lijn die getekend wordt als obstacle edit in de livesite. 

De 3Di API (backend) moet deze JSON aanleveren zodat de livesite die kan tonen.

Er moet dus een obstacle endpoint komen net als bijvoorbeeld /geosjson/culvert

### How to Reproduce?

Geen reproductie nodig.

### Add screenshots, video's etc

Endpoint als bijvoorbeeld Culvert:

![image](https://user-images.githubusercontent.com/86961942/189936690-8553ff7b-aef2-47a6-8251-54e2bb7b3cf8.png)

**Comment by lisannewapstra** [comment]
done
