### ISSUE TITLE
[Lizard/Bug]: whitescreen after clicking on value field in data management scenario page

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#11]
- [x] https://github.com/nens/lizard-management-client/issues/1018 Florian

### Complexity

moderate

### Priority

high prio

### What happened?

After clicking on any field in the Lizard>Management>Data Management>scenarios>uuid (example: https://demo.lizard.net/management/data_management/scenarios/d74b7fcb-8acb-433f-9038-83c40ad52927), a white screen appears. This blocks users for example to change the accessibility.

### How to Reproduce?

https://demo.lizard.net/management/data_management/scenarios/d74b7fcb-8acb-433f-9038-83c40ad52927

**Comment by hoanphungt** [comment]
bug fixed and deployed to production

**Comment by lexvand** [comment]
@JJFlorian Is deze melding afgemeld? Met andere woorden: Kan dit ticket gesloten worden?

**Comment by JJFlorian** [comment]
@lexvand Ja, deze kan afgemeld worden.
