### ISSUE TITLE
[3Di]: Id in breaches json should be potential_breach id

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#12]
- [x] https://github.com/nens/threedi-api/issues/1286

### Contact Details

Leendert & Martine

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=e60fc6d9-611d-4518-9330-596223c4aa52

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

API - v3 (Default)

### What happened?

Om te weten welke bres je wilt activeren is het wel zo handig om de potential breaches op de kaart te kunnen bekijken en zo de juiste te selecteren.

Om dat te doen hebben we de geojson van de breaches gedownload (/v3/threedimodels/{id}/geojson/breaches/download/). Als je die in QGIS opent, heeft die een attribuut 'id'. Die komt echter niet overeen met het id van de potential breach die je moet invullen om het event aan te maken (/v3/simulations/{simulation_pk}/events/breaches/)

De enige manier om nu aan dit id te komen is nu om in QGIS de content_pk van de breach op te zoeken in de geojson, dit vervolgens in te vullen als connected_pnt_id in de endpoint /v3/threedimodels/{threedimodel_pk}/potentialbreaches/.

Het zou een stuk makkelijker zijn als de id in de gedownloade json de id is van de potential breach. En als de attribuutnamen van de json hetzelfde zouden zijn als die van de potential_breaches die je via de API opvraagt.

### How to Reproduce?

threedimodel id: 31381 (Wetterskip Fryslan)

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Additional conversation in topdesk:
=================
Linda:
Dag Martine en Leendert.

Dit is wat we aanbieden in de API Qgis client 2.15.0 of .1. Heb je dit al geprobeerd? Zo niet zou jij dat eens willen proberen? Jonas heeft besloten dat we hier niets mee gaan doen, dus ik hoop dat je door middel van het gebruik de API Qgis client geholpen bent.
Ik hoor het graag. 

==================
Leendert z'n reactie:

Hoi,

Dit heeft niet te maken met de API Client Plugin, maar met de inhoud van de 'breaches' json die je krijgt als je het betreffende endpoint bevraagd. De features in die json hebben wel een id, maar dat id klopt niet. Het is dus een backend issue, niet frontend.

**Comment by Patrick-Nijman** [comment]
@JJFlorian Wellicht even terugkoppelen dat deze node-id's per mutatie wijzigingen. De node nummering is dynamisch. We gaan hier wel naar kijken. Maar waarschijnlijk moet dit een nieuwe feature worden,

**Comment by lisannewapstra** [comment]
out of date
