### ISSUE TITLE
[3Di]: connected_pnt_id refers to connected node id

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#13]
### Contact Details

leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7cb14914-6db2-4578-a693-47fef69e264d

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

API - v3 (Default)

### What happened?

De oorspronkelijke melding ging over de 3di Management site:
"Breach info op management.3di.live moet naar 'Connected Point ID' verwijzen, maar verwijst naar 'connection node id'
Dit zie je als je over het balkje met 'breaches' hoovert"

Voorbeeld: 
https://management.3di.live/simulations/archive/53253
Hierin is het connected node nummer 186. Dit komt overeen met de connected_pnt_id in het Potential Breach Instance api endpoint(https://api.3di.live/v3/threedimodels/31619/potentialbreaches/165376/)

Mijn eerste gedachte was dat het label in de management site 'connected node ID' verwarrend is en 'connected point id' zou moeten zijn. Patrick en Jonas gaven echter aan dat dit een backend probleem is. Als ik het goed begrijp is het probleem dus dat de connected_pnt_id eigenschap in api verwijst naar een node_id, waar dat het een point_id zou moeten zijn.

### How to Reproduce?

https://management.3di.live/simulations/archive/53253

**Comment by lisannewapstra** [comment]
out of date
