### ISSUE TITLE
[3Di]: Cannot set any date (not for radar rain and not for forecast rain) (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#134]
### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Livesite

### What happened?

I could not pick a date with the datetime picker (for a radar/ forecast rain).

### How to Reproduce?

Open a browser (happens on Chrome/ Firefox and Edge)
Select and start a model (for example v2_bergermeer_with_grndwtr #111 and template with_grndwtr
Select rain in the left toolbar
Select radar or forecast
Try to select another date/time (I tried to look for 28 July 2014 via selecting on the year and then the year range, but I think selecting any date and/ or time causes the issue).
You get undefined and NaN as date and time (and Invalid date in input field) 

If you press undefined NaN in the datetime dialog, it crashes

### What did you expect and what was the actual result?

I expected that I could use the date time picker to pick a date

### Add screenshots, video's etc

Click on a date

![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - click on 28](https://user-images.githubusercontent.com/13179397/210784099-7ec9449d-2527-4d3b-8f06-c1e13ad2c1a4.png)

# Option 1 from here

You get invalid date
Go back to not crash (click outside dialog)
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - dont click on undefined NaN](https://user-images.githubusercontent.com/13179397/210786379-902fe7e3-3246-4739-beba-dadf6338ab46.png)

# Option 2 

You get invalid date. Click on invalid date to get 4rd screenshot.
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - click on 28 - invalid date - click on it](https://user-images.githubusercontent.com/13179397/210784009-3c94dfeb-e9af-4332-a890-ac04ff65d2c3.png)

Clicked on invalid date
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - click on 28 - invalid date - clicked on it](https://user-images.githubusercontent.com/13179397/210784157-36022a66-35c6-4126-8cf2-9938d600aa14.png)

Go back to not crash (click outside dialog)
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - dont click on undefined NaN](https://user-images.githubusercontent.com/13179397/210786379-902fe7e3-3246-4739-beba-dadf6338ab46.png)

# Option 3 crash

Click on undefined NaN in dialog (top)
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - click on undefined NaN to crash](https://user-images.githubusercontent.com/13179397/210785506-96abf636-9691-4e42-9f08-58be01bad7d3.png)

Crash
![20230104 - 3di staging - datum selectie 28 juli 2014 bij bergermeer - error when crashing ](https://user-images.githubusercontent.com/13179397/210781175-a84c1459-1082-440e-8fbb-b9d842689989.png)

### Relevant log output

```shell
main.a69ceab633eaf0f4.js:2 TypeError: Cannot read properties of undefined (reading 'substring')
    at r.value (main.a69ceab633eaf0f4.js:2:5094321)
    at r.value (main.a69ceab633eaf0f4.js:2:5093979)
    at r.value (main.a69ceab633eaf0f4.js:2:5093439)
    at r.value (main.a69ceab633eaf0f4.js:2:5093006)
    at Rs (main.a69ceab633eaf0f4.js:2:5268883)
    at As (main.a69ceab633eaf0f4.js:2:5268681)
    at kl (main.a69ceab633eaf0f4.js:2:5312152)
    at _u (main.a69ceab633eaf0f4.js:2:5300185)
    at vu (main.a69ceab633eaf0f4.js:2:5300113)
    at gu (main.a69ceab633eaf0f4.js:2:5299976)
hs @ main.a69ceab633eaf0f4.js:2
n.callback @ main.a69ceab633eaf0f4.js:2
Fo @ main.a69ceab633eaf0f4.js:2
bl @ main.a69ceab633eaf0f4.js:2
_l @ main.a69ceab633eaf0f4.js:2
yl @ main.a69ceab633eaf0f4.js:2
(anonymous) @ main.a69ceab633eaf0f4.js:2
xu @ main.a69ceab633eaf0f4.js:2
lu @ main.a69ceab633eaf0f4.js:2
Ur @ main.a69ceab633eaf0f4.js:2
(anonymous) @ main.a69ceab633eaf0f4.js:2
main.a69ceab633eaf0f4.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
    at r.value (main.a69ceab633eaf0f4.js:2:5094321)
    at r.value (main.a69ceab633eaf0f4.js:2:5093979)
    at r.value (main.a69ceab633eaf0f4.js:2:5093439)
    at r.value (main.a69ceab633eaf0f4.js:2:5093006)
    at Rs (main.a69ceab633eaf0f4.js:2:5268883)
    at As (main.a69ceab633eaf0f4.js:2:5268681)
    at kl (main.a69ceab633eaf0f4.js:2:5312152)
    at _u (main.a69ceab633eaf0f4.js:2:5300185)
    at vu (main.a69ceab633eaf0f4.js:2:5300113)
    at gu (main.a69ceab633eaf0f4.js:2:5299976)
```

### Additional info

Note: does not happen on production (Chrome) (yet).
So it probably has something to do with recent changes in staging.

Did the date time for Lizard recently changed (and is it not yet adjusted to work with the datetime picker)?
Is a new version used for the datetime picker on staging?

Another note: just changing the time does work!

Good luck! :)

**Comment by GeOdin** [comment]
@Patrick-Nijman 

Hey Patrick :)

I gave this ticket priority 2 because it currently only is on staging.
But it is something a lot of people will notice without workaround (I think).

I did the same for https://github.com/nens/servicedesk-issue-only/issues/135

Kind regards

**Comment by GeOdin** [comment]
Another note: clicking on a date in the datetime picker always causes the input field (in the rain tool, outside the datetimepicker) to show Invalid date (also for all options).

**Comment by GeOdin** [comment]
Note this happens when selecting any date in the datetime picker.

For example, when not changing the date, you can create a radar rain.

![20230130 - 3di staging - create radar rain without changing date](https://user-images.githubusercontent.com/13179397/215485214-e34b242b-b684-49ba-9799-9cd2d1a1f881.png)

The rain is applied.

![20230130 - 3di staging - radar rain applied](https://user-images.githubusercontent.com/13179397/215486128-c63a4870-8657-4153-aead-506cd76e945c.png)


But when you select any date, even if it is just the same date (the date of yesterday in this example), you get NaN and undefined for dates and time. I only clicked on the date in the date input field and then clicked on 29 in the example below.

![20230130 - 3di staging - datepicker also NaN when today and applied from when not changing data](https://user-images.githubusercontent.com/13179397/215484258-88a1e9c6-2b08-42dd-a4b7-0338aea3ac11.png)

![20230130 - 3di staging - datepicker also NaN when today and applied from when not changing data 2 datepicker not defined](https://user-images.githubusercontent.com/13179397/215484229-b7c0b544-2849-4e88-94a6-052fb5db62e2.png)

**Comment by Patrick-Nijman** [comment]
Opgelost voor de release van 6 feb.
