### ISSUE TITLE
[Lizard]: No favicon for catalogue (production)

### ISSUE THREAD

**Issue by GeOdin** [nens/servicedesk-issue-only#138]
- [x] nens/nens-frontends#324

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio4 Long-term

### Lizard component

Catalogue

### What happened?

I noticed that there was no favicon for the Lizard catalogue on production.

### How to Reproduce?

Go to the catalogue https://demo.lizard.net/catalog/
Look to the tab.
There is no favicon.

### What did you expect and what was the actual result?

Would maybe be nice to have a Lizard icon.

### Add screenshots, video's etc

![20230124 - lizard catalogue production - no favicon](https://user-images.githubusercontent.com/13179397/214336609-200728bd-e697-4ced-929b-4248a63d3112.png)

### Additional info

Good luck! :)

**Comment by lisannewapstra** [comment]
done
