### ISSUE TITLE
[Bug]: Bug in geoblocks color range form field

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#14]
- [x] nens/lizard-management-client#1030

### Contact Details

Joeri

### Complexity

easy

### Priority

high prio

### What happened?

When filling in minimum or maximum color map range values lower than 0.1, the form field is buggy. For example: if you want to fill in "0.01", you end up with "1". A workaround at the moment is to fill in "0.1" first and then place a "0" in between. 

link to reproduce:
https://nens.lizard.net/management/data_management/geoblocks/new

Topdesk ticket:
https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=fca371a8-d360-4421-a605-920e47e2e6cd

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lexvand** [comment]
@JJFlorian Bug is gefixt.
