### ISSUE TITLE
[Lizard]: Raster sources related to labeltype

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#16]
- [x] nens/lizard-nxt#5384

### Contact Details

Emile, Florian, Stijn M. 

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=cd669aa3-5c81-4cfa-a726-deadd98fa300

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### Lizard component

Accounts and rights (Default)

### What happened?

Meerdere users (tot nu toe intern) lopen bij verwijderen raster sources tegen de volgende foutmelding aan: 

_Dependent label types:
/management/data_management/labeltypes/1c776839-4be5-4257-9403-e9684b058ce4_

Dat is: https://demo.lizard.net/api/v3/labeltypes/1c776839-4be5-4257-9403-e9684b058ce4/ 
Een van de rasters die niet verwijderd mag worden:  Nachthitte nieuwegein (UUID = 1d754985-3630-4c34-b68f-386fbb84d859)'

Ik snap niet hoe deze gelinkt zijn aan elkaar en hoe dat te unlinken. 

### How to Reproduce?

Delete: 1d754985-3630-4c34-b68f-386fbb84d859

### Additional info

Het valt op dat er een lange lijst deleted sources hangt aan het labeltype. 

Lex: Zo'n beetje elke source (55k+) aan dat labeltype wordt gelinkt in lizard_nxt_labeltype_raster_sources

**Comment by lexvand** [comment]
@lisannewapstra Bug is gehotfixt.
