### ISSUE TITLE
[3Di wish]: allow to specify irregular xy profiles

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#17]
- [x] https://github.com/nens/threedi-calculationcore/issues/578

### Contact Details

Kasper, Jonas

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7188c473-419a-4abe-8b98-701c54f331aa

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Other or General

### What happened?

Original request by Kasper: 
Voor WDOD moet ik ingemeten profielen in een 3Di model updaten. Nu zitten we in 3Di gebonden aan de tabulated (en dus gespiegelde) profielen waarbij het diepste punt altijd perfect in het midden ligt. Dit matcht daardoor niet altijd even goed met de praktijk.
Nu staat het me bij dat ik ergens heb opgevangen dat met de Klondike release ook ander soorten YZ-profielen kunnen worden opgegeven. Waardoor je dus niet altijd perfect gespiegelde profielen hoeft op te geven.

Reply by Jonas:
Rekenkundig gezien maakt het niks uit of het profiel regelmatig of onregelmatig is, het gaat om het doorstromend oppervlak. Ik verwacht dat er bij iwb wel tools zijn die onregelmatige profielen kunnen omzetten naar yz profielen.

Verder lijkt het me een mooi feature request voor de rekenkern als uitbreiding. Ik cc even de servicedesk om hem op te nemen in de wensenlijst

**Comment by lisannewapstra** [comment]
done
