### ISSUE TITLE
[3Di]: API_HOSTNAME not set - revision on inpy but not livesite

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#18]
### Contact Details

Emiel Verstegen (RHDHV)

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7effa6b9-508e-4775-b44f-33cbfa618c31

### Incident Type

Error

### What priority should we assign to this submission?

Prio1 Very Urgent

### 3Di component

API - v3 (Default)

### What happened?

Ik loop tegen een probleem aan dat nieuwe revisies wel door inpy heen komen maar vervolgens niet op de livesite worden getoond (en ook niet als threedimodel in de API zijn opgenomen). Ik heb ook een oude (werkende) revisie opnieuw gecommit en die komt er ook niet door.

Bijvoorbeeld station-zuidzijde-station_zuidzijde_default-5-14fc79506c2ba976c601f751171c683c0deee4bd staat op succes en is een exacte kopie van #1 die wel op de livesite beschikbaar was (alleen de name in global_settings aangepast).
In de logging van #4 in dezelfde repository zie ik dit staan, misschien heeft het ermee te maken. Bij #5 zag ik die echter niet meer staan (ik had zelf wat modellen gedisabled) en komt hij ook niet op de livesite.
2022-02-01 10:01:03,702 - threedi_model.revision - WARNING - API_HOSTNAME not set, could not disable model

Met vriendelijke groet,

Emiel Verstegen

### How to Reproduce?

Upload a new revision

### What did you expect and what was the actual result?

SUCCESS on inpy--> Available on livesite

**Comment by Patrick-Nijman** [comment]
@lisannewapstra het top desk ticket is ondertussen gesloten. Moet ik dit nog verder oppakken?

**Comment by lisannewapstra** [comment]
nee, deze had ik zelf ook al wel kunnen sluiten
