### ISSUE TITLE
[Bug]: Each line in a csv export from graph ends with a separator

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#2]
### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=364e2527-da8f-4096-a04a-632c851e63d4

Topdesk ticket 2111 0004: 

### Complexity

moderate

### Priority

low prio

### What happened?

The csv export from the plot data (see pic below) results in a buggy csv. Each line ends with a separator, see attached csv file.
![image](https://user-images.githubusercontent.com/73856313/141144559-e5d57668-8eb0-4aba-b2d9-da66faf02eaa.png)
[discharge_flowline_181965 (2).csv](https://github.com/nens/ThreeDiToolbox/files/7514025/discharge_flowline_181965.2.csv)

Bug is in dependency pyqtgraph.

**Comment by Patrick-Nijman** [comment]
We might make a workaround but this is an issue in a repo we are not maintaining. So if we construct a workaround and they fix the issue we will have to change our code as well. I will keep an eye on this maybe we can make a clause where we are not using the last ; anyway.
