### ISSUE TITLE
[Lizard]: wishes: Step geoblock for geometries & isMissing geoblock

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#20]
### Contact Details

Krol

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=fbd14eb7-b38b-42bf-b1ae-8ebf9bc505fc

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Other or General

### What happened?

Originele aanvraag:

De eerste is een Step geoblock voor de geometries. Voor de rasters bestaat deze al en deze wordt in de praktijk veel gebruikt omdat we vaak een raster in 2 klasses willen opdelen. Voor de geometries doen we dit ook vaak maar dat kost nu veel meer stappen.

Tweede is een isMissing geoblock, handig voor zowel rasters als geometrieen. Ook daar zijn wel trucs voor om die met de huidige geoblocks te maken, maar ook die kosten veel stappen en werken net niet handig.

### How to Reproduce?

x

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment]
Hoi,

Ik zou graag wat meer info willen hebben om deze feature request in te schatten:

- `Step` Functie op een geometry block; ik denk dat je gedoelt dat de stapfunctie een eigenschap van een geometrie (een getal) als invoer moet nemen, en de uitvoer in een andere eigenschap wegschrijft? Waarom kan je https://dask-geomodeling.readthedocs.io/en/latest/geometry.html#dask_geomodeling.geometry.field_operations.Classify daar niet voor gebruiken?
- `IsMissing` voor rasters: deze bestaat al: https://dask-geomodeling.readthedocs.io/en/latest/raster.html#dask_geomodeling.raster.elemwise.IsNoData
- `IsMissing` voor geometrieën: gaat dit om de geometrie zelf of om een eigenschap van een geometrie?

**Comment by lexvand** [comment]
@JJFlorian Ik heb contact gehad met Martijn. Het kon opgelost worden met bestaande functies (Steps met Classify en IsMissing met Where). Het ticket kan afgesloten worden.
