### ISSUE TITLE
[3Di]: Simulation time rendered incorrectly in 3Di management page

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#21]
- [x] https://github.com/nens/nens-frontends/issues/235

### Contact Details

Leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=edb4f42c-da8d-4c11-8769-66dc5a6f57cf

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Other or General

### What happened?

Onderstaande simulatie (gem. Groningen) laat zien dat de simulatieduur 3329 s is (lijkt me een logische waarde). Maar de simulation start en end timestamps geven aan dat de simulatie ~100 jaar duurde:

Start
2/4/2022, 2:51:39 PM

End
1/11/2122, 2:51:39 PM

https://management.3di.live/simulations/archive/59024

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
done
