### ISSUE TITLE
[Klimaatmonitor]: Replace klimaatcatalogus icon with a download icon 

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#22]
### Contact Details

Jelmer

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=f4019140-34db-4726-9889-8e5135503786

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Powered by Lizard Klimaatatlas

### What happened?

Original request:

Can the klimaatcatalogus icon be replaced by a download icon? Jelmer received various feedback about the hard to find download button.

**Comment by Patrick-Nijman** [comment]
@JJFlorian Volgens mij is de download icon nu een stuk duidelijker. En volgens mij kan dit issue dus gesloten worden. Kun je dit even checken?
