### ISSUE TITLE
[Bug]: Legend not complete in Viewer compared to categories in map and defined in colormap

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#25]
### Contact Details

Annelies Hommersom, Water Insight (Topdesk 2108 0117)

### Complexity

moderate

### Priority

low prio

### What happened?

![image](https://user-images.githubusercontent.com/33685743/154713552-0fe68eab-c60d-4d30-85c0-7893cd63d93f.png)

- In the legend you see blue, green and 'other'.
- In the map you see blue, green, yellow and orange
- The colormap used says

{"data": [[0, [0, 103, 251, 255]], [1, [9, 234, 1, 255]], [2, [255, 254, 0, 255]], [3, [255, 181, 0, 255]], [4, [255, 10, 0, 255]]], "type": "DiscreteColormap", "labels": {"nl_NL": [[0, "Zeer goed"], [1, "Goed"], [2, "Matig"], [3, "Ontoerijkend"], [4, "Slecht"]]}, "invalid": [255, 255, 255, 0]}

Zooming in you get

![image](https://user-images.githubusercontent.com/33685743/154713869-2493aa60-936e-40e0-893d-0dd7dd78f497.png)

### How to Reproduce?

https://waterinsight.lizard.net/viewer/favourites/85b9757b-860d-4af3-a5f8-e1aa1a5e3bb5

### What did you expect and what was the actual result?

I would expect to see this 
![image](https://user-images.githubusercontent.com/33685743/154714140-28f6e12a-e966-4dbd-9d56-0b3b34671d9b.png)

And I do not understand the 'other' category. When/why does it show?

### Additional info

Red is also not visible, but I can't see it without zooming in as well. 

Raster layer = KRW Lauwersmeer (Water Insight, shared with N&S technology), uuid=8523542b-9105-40f6-80be-09cba5dbb0ce

**Comment by lisannewapstra** [comment]
@lexvand  misschien kan jij al iets zeggen

**Comment by lexvand** [comment]
The legend is generated based on a raster-aggregate request for the bbox of the area on screen. This way we always show the most relevant classes for nominal and ordinal data. Here we run into a downside of this method, as can't make a very detailed request for all available classes. That would not be responsive enough. We choose to do a coarse request, which means we loose information on classes that cover less than 2% of the area.

It is a valid use case to be able to see the full legend when a user wants to. We are not going to change this in the current version of the viewer as it would be too invasive. We will take this into consideration for the new version that we are going to develop this year.

**Comment by lisannewapstra** [comment]
out of date
