### ISSUE TITLE
[3Di]: Nodatavalue in livesite shown as actual value

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#28]
- [x] https://github.com/nens/threedi-live-site/issues/989

### Contact Details

Stijn O

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=9e2d214c-11fc-4eeb-9bc7-a1e7938ad836

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Livesite

### What happened?

The nodata value outside the raster is shown as its actual value (9999?). See figure for clarification.
![image](https://user-images.githubusercontent.com/73856313/155531834-f2ccc673-6a6a-4223-ae71-abf3c98e1eaa.png)

**Comment by lisannewapstra** [comment]
done
