### ISSUE TITLE
[Bug]: Opening the DEM editor in the livesite causes a whitescreen

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#29]
### Contact Details

Florian

### Complexity

moderate

### Priority

high prio

### What happened?

Whitescreen when editing de DEM layer in the livesite

**Comment by Patrick-Nijman** [comment]
@JJFlorian Deze informatie is echt te summier. Ik wil sowieso reproduce hebben en een screenshot van dit soort zaken. Op deze manier is dit niet te fixen....

**Comment by JJFlorian** [comment]
@Patrick-Nijman Deze bug was al besproken en dus bekend. Ik had hem voor de volledigheid ook in deze repo geplaatst. 

Hij was ook vrijwel direct gefixt, dus deze kan gesloten worden
