### ISSUE TITLE
[Lizard]: Open combined graphs with a single url

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#34]
### Contact Details

Ivar/Emile

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=e0d8946f-ae98-45a9-9e20-cf302b420de1

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Viewer

### What happened?

Ivars origineel verzoek: 

Is het mogelijk om grafieken standaard gecombineerd te openen (vanuit een doorlink URL). Met favorieten is dit mogelijk dus waarschijnlijk ook met een custom url (https://demo.lizard.net/viewer/nl/charts/topography,assetgroup$9c2d7b6/point/measuringstation$53/@52.1858,5.2677,8/-2Days0Hours+0Days3Hours) dit format. Het gaat om zo'n 1300 locaties dus voor alles een favoriet aanmaken is geen (Reeele) optie.

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lexvand** [comment]
@JJFlorian This is not something we can support with the current Viewer. We will consider it for the new version we're currently designing.

**Comment by lisannewapstra** [comment]
out of date
