### ISSUE TITLE
[3Di]: allow user to set names when using 'multiple simulations'

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#35]
### Contact Details

Arnold

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=8a984963-047d-4d5c-bfe8-75242b7b845a

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Arnold wishes to be able to set his own name per simulation when using the 'multiple simulations' option. At the moment the names are auto generated as the simulation name + a _1, _2 etc 'extension'. 

This will make it easier to distinguish multiple simulations.

**Comment by Patrick-Nijman** [comment]
@JJFlorian The simulations are already distingiushed by the simulation name. What kind of pattern is Arnold suggesting? It's a lot of work to make an wildcard system without really knowing what value should be variable and why this is more distinguishable then a normal addition

**Comment by JJFlorian** [comment]
No response from Arnold; closed
