### ISSUE TITLE
[3Di]: Local rain does not work - "STARTED"

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#39]
### Contact Details

Virtual City Systems (zyao@vc.systems) or Joeri

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7f35e74f-7ac4-4b24-aa2d-2d4b5f711bee

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

API - v3 (Default)

### What happened?

https://api.3di.live/v3/simulations/65133/events/

I’m (Zhihang Yao) currently testing the the Constant Local Rain of the 3di-live API. I am able successfully create a local rain event like this:

![image](https://user-images.githubusercontent.com/33685743/160161921-d8315ddf-e153-4b43-aac5-20799f93aa93.png)

After that, I start the simulation via the 3di-live web application https://www.3di.live/. The simulation was unfortunately hanging always at the “STARTING” status and cannot be started. See below

![image](https://user-images.githubusercontent.com/33685743/160161921-d8315ddf-e153-4b43-aac5-20799f93aa93.png)

Do you have any ideas how to get around this issue? Some problem in the 3Di-Live backend?

### How to Reproduce?

Florian:
https://api.3di.live/v3/simulations/65379/events/ 3di livesite simulatie: runt
https://api.3di.live/v3/simulations/65391/events/  basisclone
https://api.3di.live/v3/simulations/65395/events/ clone#2 waar aanpassingen aan kunnen gemaakt worden

### Additional info

Joeri & Virtual city systems hebben hier haast mee, omdat hun project hierdoor stilligt. Volgens Jonas minder prio, omdat het maar 1 gebruiker is. 

Local rain is blijkbaar door niemand getest/gebruikt nog.

**Comment by Jonasvsl** [comment]
continued in this ticket. don't know how this normally works:
https://github.com/nens/threedi-api/issues/1611

**Comment by Jonasvsl** [comment]
wat ik nog extra gedaan heb:
een nieuwe simulatie gedraaid met als tag 'debugmode'

met dit endpoint
/v3-beta/simulations/from-template/
aangezet, hier de template id opgezocht: https://management.3di.live/schematisations/385/10392
en dan local rain aangezet voor noordpolder model

ik kom niet eens tot de start van het model, maar met hulp van Jelle de bug snel gevonden

**Comment by Patrick-Nijman** [comment]
@Lisanne AFAIK this issue has been resolved a couple of weeks ago (Mid june) Can you close this issue if that's the case and if not notify me and explain what needs fixing?

**Comment by lisannewapstra** [comment]
Works indeed!
