### ISSUE TITLE
[Lizard]: Viewer raster export results in nodata-value of 1.79e+308 instead of -9999

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#4]
### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=b989536b-4c27-4d97-b1ce-7fb245932da3

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Viewer

### What happened?

When exporting a 3Di raster from the Lizard viewer, the no data value is set to 1.79769e+308in stead of -9999. 

### How to Reproduce?

w0156-hulsbergerbeek-compleet-t100-v3-max-water-depth.tif was provided as example. Export the file from the viewer and either open in qgis or check with the gdalinfo commant in the OSgeo4W shell.

### What did you expect and what was the actual result?

See above

### Add screenshots, video's etc

![a](https://user-images.githubusercontent.com/73856313/141984543-3fbf93f0-6523-4a98-8c21-b2a4781987c9.PNG)
![b](https://user-images.githubusercontent.com/73856313/141984561-981b08e5-7775-4a59-8163-16c48c2d39f3.PNG)
![image](https://user-images.githubusercontent.com/73856313/141984924-b07473e4-caa1-4c9d-b1e7-a63d57c5cc6c.png)

### Additional info

The 1.79e308 value seems to be recognized by both qgis and the viewer and doesn't cause any problems in the data visualization.

**Comment by lexvand** [comment]
The export in the Lizard viewer makes use of API v3, which has no option to choose your own nodata value. It defaults to the nodata value of the store, which is determined by the post-processing method.

In API v4 we added this option, but the current viewer is not going to be rewritten to make use of that. It could be a feature for a future new version of the viewer.

For now the only way to get the preferred result is to export directly from API v4. For non-scenario raster layers the catalogue can be used, which is based on API v4.
