### ISSUE TITLE
[3Di]: initial ground water level raster not included in simulation?

### ISSUE THREAD

**Issue by Overmeen** [nens/servicedesk-issue-only#40]
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/mango/window/0?t=1648468933202

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

API - v3 (Default)

### What happened?

Simulations seem to start without initial ground water level, even though an initial ground water level raster is present in the schematisation. Concluded from the fact that there is no initial storage in the groundwater domain at the start of the sim (read from the flow summary), and all the graphs of the water level at the groundwater nodes begin empty (no water level).

This seems to be the case through calculating via the MI and via the livesite. It also seems to be the case for more schematisations. 

The raster seems to be uploaded successfully and included in the events. 

Examples: (different models from different schematisations):
https://api.3di.live/v3/simulations/65592/events/
https://api.3di.live/v3/simulations/65600/events/ 

### How to Reproduce?

.

### What did you expect and what was the actual result?

.

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment]
I can confirm this from the logs, the groundwater initial waterlevels are set on open water cells:

```
INFO:calccore.calccore:Initializing calccore
INFO:calccore.calccore:Starting calccore loop
INFO:calccore.calccore:Fortran log level will be set to INFO 
INFO:calccore.calccore:Simulation config from API will be used...
** INFO   : ___________________WELCOME TO THE WONDERFUL WORLD OF 3Di___________________
** WARNING: No inflow administration file. Inflow will be discarded.
** INFO   : Number of threads used for calculation is:              1
INFO:calccore.calccore:Will add initial states now...
INFO:client.models.forcings:Initial state initial waterlevel 2d_open_water: [0. 0. 0. ... 0. 0. 0.] m MSL has been set
INFO:client.models.forcings:Initial state initial waterlevel 1d: [0. 0.] m MSL has been set
```

I double checked whether the logs are correct, but for groundwater level it should show `Initial state initial waterlevel 2d_groundwater: .... has been set`

I'll open a bug in threedi-api.

**Comment by Patrick-Nijman** [comment]
Orphin Issue that should be closed
