### ISSUE TITLE
[3Di]: update 3Di result mail

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#42]
- [x] https://github.com/nens/lizard-nxt/issues/5849

### Contact Details

Lisanne

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=905bb807-c805-4997-a0fc-128c5b9b9765

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Results in Lizard

### What happened?

Lisanne proposes to update the 3Di results mail by linking to the Catalogue. Here, one can find the links to api, viewer and management screens.

Example of the current mail:

Dear 3Di user,
Your model results "2022-03-25T134551_noordpolder_default2_lisanne.wap" of model "demo_org_noordpolder-noordpolder_default2-1-e1188d09b13701c4d2fdc620e5bac103079b05d2" have been processed successfully into the Lizard Scenario Archive. You can download the raw model result files from:
[results-3di](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvcmVzdWx0cy9yZXN1bHRzXzNkaS5uYyIsImV4cCI6MTY0ODgxNzI3Mn0.pKPXoFR-Dbr0tZ4-HVoHs_93_oZOIFnaBZ-egrKRZLM)
[grid-admin](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvZ3JpZGFkbWluLmg1IiwiZXhwIjoxNjQ4ODE3MjcyfQ.x0E55azse3D2lbFHyEqqkVCnuM7kmEALWKdAKAdIOjU)
[logfiles](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvcmVzdWx0cy9sb2dfZmlsZXMuemlwIiwiZXhwIjoxNjQ4ODE3MjcyfQ.LvkK8kRPBw6IFaQrzpZtXXcYeZq7ZUT-A2Nm9nb63K4)
These links will be available for seven days.
If you have a Lizard subscription the results will be stored in Lizard at https://demo.lizard.net/. Add the layer "2022-03-25T134551_noordpolder_default2_lisanne.wap" in the layer menu to see your processed modeling results.
If you would like to access the model results through the Lizard API, use the following UUID: [af0024c6-006d-415c-99de-0119830d55c4](https://demo.lizard.net/api/v3/scenarios/af0024c6-006d-415c-99de-0119830d55c4/). For scenario management, use:https://demo.lizard.net/management/data_management/scenarios/af0024c6-006d-415c-99de-0119830d55c4.

Proposed mai:

Dear 3Di user,
Your model results "2022-03-25T134551_noordpolder_default2_lisanne.wap" of model "demo_org_noordpolder-noordpolder_default2-1-e1188d09b13701c4d2fdc620e5bac103079b05d2" have been processed successfully into the Lizard Scenario Archive. You can download the raw model result files from:
[results-3di](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvcmVzdWx0cy9yZXN1bHRzXzNkaS5uYyIsImV4cCI6MTY0ODgxNzI3Mn0.pKPXoFR-Dbr0tZ4-HVoHs_93_oZOIFnaBZ-egrKRZLM)
[grid-admin](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvZ3JpZGFkbWluLmg1IiwiZXhwIjoxNjQ4ODE3MjcyfQ.x0E55azse3D2lbFHyEqqkVCnuM7kmEALWKdAKAdIOjU)
[logfiles](https://demo.lizard.net/api/v4/files/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlcGF0aCI6Ii9tbnQvbGl6NnByb2QvM2RpX3Jlc3VsdHMvMjMxNDYvcmVzdWx0cy9sb2dfZmlsZXMuemlwIiwiZXhwIjoxNjQ4ODE3MjcyfQ.LvkK8kRPBw6IFaQrzpZtXXcYeZq7ZUT-A2Nm9nb63K4)
These links will be available for seven days.
If you have a Lizard subscription the results will be stored in Lizard at https://demo.lizard.net/catalogue/?data=Scenario&uuid=af0024c6-006d-415c-99de-0119830d55c4.

**Comment by lisannewapstra** [comment]
done :)
