### ISSUE TITLE
[3Di]: check timestep differences between 1d and 2d bc

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#43]
- [x] https://github.com/nens/threedi-modelchecker/issues/189

### Contact Details

Wayne

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=9c26942e-beb2-4ae8-a3ee-a8c65f25ae14

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?
Wayne tried to upload a model with a timestep difference between the 1D and 2D boundary conditions. This should be caught by the check model function, but it did not. The actual upload did come with a error message but the model did manage to upload. Therefore it shows up on the management screens and the livesite, but it has no template: so it cannot be used for a simulation.

### How to Reproduce?
The screenshots wayne provided:
![wayne1](https://user-images.githubusercontent.com/73856313/167139038-9bb87fa7-da86-433e-a16b-884688f3648b.png)

![wayne2](https://user-images.githubusercontent.com/73856313/167139026-8deaef07-7b1c-421d-82f3-9e19bbbb26cd.png)

### What did you expect and what was the actual result?
The error should be caught by the model/schematisation checker.  Some users tend to ignore the error messages and asking why the model on the livesite but cannot be used...

**Comment by lisannewapstra** [comment]
done
