### ISSUE TITLE
[Lizard]: href value of 'Bekijk in site'/'see in site' button is None.

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#5]
### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=42fc8365-ba73-459c-86e2-ccec3939da21

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Powered by Lizard Klimaatatlas

### What happened?

The 'see in site' button does not work

### How to Reproduce?

https://demo.klimaatatlas.net/ -> overzicht atlassen -> 'bekijk in site' button

### What did you expect and what was the actual result?

Expected: open the lizard viewer
actual result: opens https://demo.klimaatatlas.net/None/

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/142613817-75c0a261-c7a4-4bdd-ae1e-5102af192640.png)

### Additional info

Anything else you would like to share?

**Comment by lexvand** [comment]
I've seen this issue before. It seems like a configuration error at first sight, but is actually a client bug.

This version of the Klmaatatlas is end-of-life and is being replaced, so it will not be fixed anymore.
