### ISSUE TITLE
[3Di]: new user is redirected to api root after signing up

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#58]
- [x] https://github.com/nens/threedi-api/issues/1659

### Contact Details

Florian

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Contract & Accounts

### What happened?

When a new user signs up, he/she is directed to the api root. This doesn't make sense; should be the management screen or the livesite

### How to Reproduce?

* Add a new user in for example https://api.3di.live/management/users/61f5a464c35044c19bc7d4b42d7f58cb/
* Open the link in the invitation email
* press sign up, to make a new account
* Fill in information
* enter the invitation code which is sent to the email adres

### What did you expect and what was the actual result?

I expected the new user to be redirected to the management screens. Now a user is redirected to the api root. Sometimes this even causes an error, see screenshots

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/168085067-44bfd37d-a02e-4879-abc4-63e9b6eb61ce.png)

### Additional info

Anything else you would like to share?

**Comment by Patrick-Nijman** [comment]
Uitgerolt op staging. Gaat vrij rap naar productie
