### ISSUE TITLE
[3Di]: bug in changing Duration until max depth for breaches in livesite

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#60]
- [x] https://github.com/nens/threedi-live-site/issues/1006

### Contact Details

Stijn O

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=32fd9694-9174-4fcd-8127-74532af82f9b

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

If you want to change the duration until max depth for breaches in the livesite, points and comma's do not come through. It often changes to a NaN value.

### How to Reproduce?

1 open livesite
2 open a model with breaches, for example hl_handelingsperspectief_38breslocaties - HL_handelingsperspectief_38breslocaties_test (2) #15
3 zoom in to a breach, click on it and click on edit settings

### What did you expect and what was the actual result?

be able to fill in floats

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/172372991-ca22915a-22ff-455e-97e2-823327cf347b.png)

**Comment by lisannewapstra** [comment]
done
