### ISSUE TITLE
[3Di]: feature request: load profiles into a existing 3di model

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#61]
- [x] https://github.com/nens/threedi-schematisation-editor/issues/63 

### Contact Details

stijn o

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=934d3e7b-5792-4dce-aa9f-19efabb9f0de

### Incident Type

Wish

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Modeller Interface (QGIS)

### What happened?

For a specific project, Stijn created a script to load profiles into an existing 3di model. Alexander and Leendert requested him to make a feature request. He has send the python script (see the topdesk ticket). the script was made by using the threedi_raster_edits. The script makes cross section definitions and locations, edits the channel with a vertex at the cs location and deletes old cross sections. 

The proposal is to make this a feature of the MI/processing tools, so the user can upload a csv file with profiles (name, distance, z) and coordinates.

### How to Reproduce?

Na

### What did you expect and what was the actual result?

NA

### Relevant log output

```shell
NA
```

### Additional info

NA

**Comment by lisannewapstra** [comment]
done
