### ISSUE TITLE
[Lizard]: Resource not found. #404.10", No Timeseries matches the given query error in timeseries/percentiles endpoint

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#62]
- [x] nens/lizard-nxt#5540

### Contact Details

Philippine

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=b1585ab7-64eb-4435-a3d9-c902b8b6fb55

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

API

### What happened?

When providing a start and end date in the query, the response is the following error:

"status": 404,
    "code": 10,
    "message": "Resource not found. #404.10",
    "detail": "No Timeseries matches the given query."

### How to Reproduce?

Example:
https://nens.lizard.net/api/v4/timeseries/c4d1b302-7f53-463b-9259-77eef600e03e/percentiles/?percentiles=2,98&start=2010-01-01T00:00:00Z&end=2013-01-01T00:00:00Z

### What did you expect and what was the actual result?

We expect percentiles in the given time period. The percentiles are correctly given if the start and end parameters are not provided.

Happens for all timeseries

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lexvand** [comment]
@JJFlorian This has been fixed in yesterday's release.

**Comment by lexvand** [comment]
@JJFlorian Closing this issue as it has been fixed.
