### ISSUE TITLE
[3Di]: display name of an asset partly readable in livesite

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#63]
- [x] https://github.com/nens/threedi-live-site/issues/1007

### Contact Details

Leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=b6807560-4d9b-4502-b777-c0d79c36b211

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

If one selects an asset in the livesite, the name is barely visible. The line of text is not responsive, so only the first 20 characters are visible.

### How to Reproduce?

example:
open Ravi River Himachal Pradesh #3 in livesite.
search "weir" and select the first option

Result:
![image](https://user-images.githubusercontent.com/73856313/172873594-594d0b2a-9aff-43e9-a8e5-ce1fe824ff3f.png)

### What did you expect and what was the actual result?

Responsive text or hover option with full name

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
done
