### ISSUE TITLE
[3Di]: bug in livesite when initial discharge coefficient of weir is 0

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#64]
- [x] https://github.com/nens/threedi-live-site/issues/1008

### Contact Details

Leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=7600059f-5d22-43bb-8a99-211841cd0dc8

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

If a model has a weir with an initial discharge coefficient of 0, it is impossible to open the weir. If the weir is selected, the editing button pressed and the status dropdown opened, it is impossible to select open. 

### How to Reproduce?

In the livesite open Ravi River Himachal Pradesh #3
search for 'weir' and select the top weir
click on edit button and try to open the weir.
Even if you click on 'open', the closed option remains selected

### What did you expect and what was the actual result?

I expected it to work

### Add screenshots, video's etc

![image](https://user-images.githubusercontent.com/73856313/172876043-82c95cd7-dec6-497a-8b0b-3c14bae36385.png)

### Additional info

A workaround was to add a weir which had an initial value, with an offset to change back to 0 after a certain time. This works, as long as not a file control is being used; the livesite does not check the livesite, which should be the case anyways

**Comment by lisannewapstra** [comment]
done
