### ISSUE TITLE
[3Di]: Amount of available results to download in management screens is incorrect; should filter out deleted results

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#66]
- [x] https://github.com/nens/threedi-api/issues/1729

### Contact Details

Marleen

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=ee36b440-01dc-4dfa-9031-e9024f57d5c6

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Other or General

### What happened?

The amount of available results for a given simulation sometimes don't match with the actual amount of available results. 

### How to Reproduce?

Example: 
simulation for groningen: https://management.3di.live/simulations/74960
It says 
![image](https://user-images.githubusercontent.com/73856313/174789157-d73c31ec-a963-4aed-a663-e726cc7c1b92.png)

But only has 2 results available: 
![image](https://user-images.githubusercontent.com/73856313/174789224-9505742d-8ccf-4bd1-ad0c-acd8e5d4f511.png)

This is probably caused because 2 files are found in the api, but have a state of 'file has been removed'
![image](https://user-images.githubusercontent.com/73856313/174789399-bb2e25d0-f432-4ff7-92aa-6911aad7eb06.png)

### What did you expect and what was the actual result?

The amount in the button should be filtered for removed files. 

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
done?
