### ISSUE TITLE
[3Di]: Total balance in water balance tool does not work in MI 3.22

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#67]
- [ ] https://app.zenhub.com/workspaces/lutra-61e574104cc38a001fb287de/issues/nens/threeditoolbox/659

### Contact Details

Rebecca

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=bf87655c-40ab-4ad9-97ef-bbec70be7192

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

The total balance option in the water balance tool gives no results, see pic. This only applies for MI 3.22

![image](https://user-images.githubusercontent.com/73856313/175312252-cb05cfc8-656e-4121-b6c0-479b341d9194.png)

### How to Reproduce?

Install the MI 3.22, download for example the model of https://management.3di.live/schematisations/5534/40755 and import the model+results in the MI. Select a random area to use the water balance tool and press the total balance button.

Will result in empty graphs

### What did you expect and what was the actual result?

I expected something, but the result was nothing

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

I tried the water balance tool in the MI 3.16 for the exact same model+results, which worked:

![image](https://user-images.githubusercontent.com/73856313/175313028-f9fc2b24-9995-4920-9b29-1ad8342eb0c8.png)

**Comment by leendertvanwolfswinkel** [comment]
Has been fixed, will be part of the upcoming release (I expect 2 weeks)
