### ISSUE TITLE
[Lizard]: Damage estimator - calculation questions

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#69]
### Contact Details

w.vangerwen@hhnk.nl

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=da16cd9c-39cc-45ed-9365-d41366151e8f

### Incident Type

Question (Default)

### What priority should we assign to this submission?

Prio2 Urgent (liefst binnen 2 weken een antwoord)

### Component

Lizard - Damage estimator

### What happened?

Wietse (HHNK) has some questions about the calculation of Lizard-damage, which the service desk cannot answer. 

1. 
De gamma-factoren duur, herstelperiode en maand worden gekozen op basis van de gebruikersinput. Wat doet lizard als er een inundatieduur van bijvoorbeeld 48 uur meegegeven wordt? We geven bijv standaard dit mee bij 3Di berekeningen: 

> {…"damage_estimation": {
> "cost_type": 2,
> "flood_month": 9,
> "inundation_period": 48,
> "repair_time_infrastructure": 120,
> "repair_time_buildings": 240
> }}

In de tabel staat namelijk 1dag en 3 dagen, gebruikt lizard dan lineaire interpolatie tussen de gamma-waarden? Dus tussen 0.1 en 0.33 in dit voorbeeld.

2.

Bij inundatiediepte gaat dat iig wel zo voor zover ik het begrijp. Maar waarom is de eerste waarde dan -0.01? Dan krijg je bij een waterdiepte van 0 dus een gamma_inundatiediepte van 0.5?

3.
Hoe wordt de inundatiediepte meegenomen bij het berekenen van de indirecte schade (voor gebouwen)? Stel een herstelperiode van 10 dagen. Dan is de gamma voor bijv. 'woonfunctie' = 1. Indirect_gem* gamma_herstelperiode geeft dan altijd schade. Ook als er geen inundatie is. Waar ligt dan de grens wanneer er indirecte schade ontstaat? Inundatiediepte>0cm? >1cm?

### Already done?

I searched in the Lizard repo, but can not make sense of it.
Also could't find anything in the STOWA WSS documentation or 3Di documentation (https://docs.3di.live/d_scenario_archive.html#damage-estimation en bij https://www.waterschadeschatter.nl/damage/.).

repo lizard wss = https://github.com/nens/damage-estimator

mogelijk interessant
https://github.com/nens/damage-estimator/blob/master/damage_estimator/tasks.py
https://github.com/nens/damage-estimator/blob/master/damage_estimator/parsers.py
https://github.com/nens/damage-estimator/blob/master/damage_estimator/lookups.py

### Additional info

 gamma = reductiefactor, zie https://www.waterschadeschatter.nl/static_media/lizard_damage/help/schadeberekening.pdf

**Comment by lexvand** [comment]
@arjanverkerk Kun jij hier wat duiding op geven?

**Comment by arjanverkerk** [comment]
1. Klopt, de gamma_inundatiediepte en gamma_inundatieduur worden lineair geïnterpoleerd tussen de gespecificeerde waarden in de schadetabel.
2. Inderdaad, voor de meeste BRP functies is de gamma_inundatie 0.5 als de waterstand 0 is.
3. De indirecte schade wordt berekend voor alle cellen waar een inundatiediepte groter dan 0 is (voor de liefhebbers, hier gebeurt het in de code: https://github.com/nens/damage-estimator/blob/master/damage_estimator/lookups.py#L295). Een uitzondering vormen spoor en wegen, maar omdat bij mijn weten het betreffende raster op dit moment niet is gevuld, wordt daar nu helemaal geen indirecte schade voor berekend.

**Comment by arjanverkerk** [comment]
De `gamma_herstelperiode` wordt trouwens helemaal niet gebruikt in Lizard; het bedrag (/m2/dag) wordt (effectief) gewoon vermenigvuldigd met het aantal dagen en vierkante meters en daar is verder geen korting meer op voor kortere inundaties, wat de `gamma_herstelperiode` hier en daar lijkt te suggereren.
