### ISSUE TITLE
[Bug]: Simulation with lizardrasterrain event freezes at (0%)

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#7]
- [x] https://github.com/nens/threedi-api/issues/1254

### Topdesk
 
Topdesk: https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=76abc729-febd-49aa-be7b-194470cd91f5

**Comment by Patrick-Nijman** [comment]
Lizard raster rain interval looks to be 0 (zero), can anyone check this in Lizard? @lisannewapstra @JJFlorian

**Comment by lisannewapstra** [comment]
Is that a check 3Di does? 
https://demo.lizard.net/api/v4/rasters/?name=Regen
   "interval": "00:05:00",
However, this layer is special and built up of 3 layers: 5min, 1h and 24h interval.
