### ISSUE TITLE
[3Di]: Opening a schematisation in management screens redirects to schematisations/{schem_id}/new

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#78]
- [x] https://github.com/nens/nens-frontends/issues/236

### Contact Details

Marleen

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=ded7363b-b493-4973-a7ac-ac6fec299a33

### Incident Type

Error

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Other or General

### What happened?

Sometimes (I cannot define when and when not), when opening a schematisation from the overview in the management screens, the user is directed to the schematisations/{schem_id}/new path

### How to Reproduce?

Marleen experiences this problem with for example https://management.3di.live/schematisations/5599/new

### What did you expect and what was the actual result?

She expects the revision page to open, but she lands on a >new page, which only shows a delete button

![image](https://user-images.githubusercontent.com/73856313/181758415-67833db2-5b94-4d85-8e71-95b08239bf08.png)

After pressing the schematisation id a couple time, she lands on the correct page.

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
done
