### ISSUE TITLE
[3Di]: Remove warning on > 1e9 cells

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#79]
- [x] https://github.com/nens/threedi-api-qgis-client/issues/393

### Contact Details

Stijn O

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=27663279-4610-443d-a19c-c6e4c06afd49

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio4 Long-term

### 3Di component

Modeller Interface (QGIS)

### What happened?

Stijn received a warning on having more than 1e9 cells in his raster. However, Nici and Martijn claim that this shouldnt be a problem anymore since Klondike.

Stijn proposes to remove the warning to avoid users unnecessarily removing their rasters.

### How to Reproduce?

Use a raster with >1e9 cells

**Comment by leendertvanwolfswinkel** [comment]
Is een probleem van de raster checker. Eén van de (vele) redenen waarom we die willen aanpakken.

Hij kan deze rasters gewoon uploaden als hij de raster checker errors negeert

**Comment by lisannewapstra** [comment]
done
