### ISSUE TITLE
[3Di]: Make waterdepth map transparent in livesite

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#8]
### Contact Details

Joep

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=e11e7346-23ea-48c8-a0bc-256c8063eb10

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Livesite

### What happened?

Currently the watherdepth map is not transparent in the livesite. Joeps wish is to make it so.

### How to Reproduce?

3Di livesite

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
out of date
