### ISSUE TITLE
[3Di]: using an existing sqlite when making new schematisation incorrectly transfers raster locations

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#80]
- [ ] https://github.com/nens/ThreeDiToolbox/issues/696

### Contact Details

Sjon

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=9d8bc81e-0e7f-4ea2-83e2-f2a599dc5cc1

### Incident Type

Error

### What priority should we assign to this submission?

Prio2 Urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Sjon experiences problems when he tries to create a new schematisation and uses an existing spatialite. The problem comes down to incorrect raster location names, because of using a \ iso a /. 

![image](https://user-images.githubusercontent.com/73856313/181771414-41472617-bd39-4885-b3d7-84e86100b1ee.png)

### How to Reproduce?

1) Download any schematisation which contains one or more rasters.
2) Create a new schematisation and use the Choose file option for the spatialite
3) The rasters in the old schematisation are copied to the new one, but have a wrong filepath in the global settings

### What did you expect and what was the actual result?

One would expect the filepaths to be correct and the new schematisation to upload w/o problems

**Comment by leendertvanwolfswinkel** [comment]
Is een probleem van de raster checker. Eén van de (vele) redenen waarom we die willen aanpakken. 

Hij kan deze rasters gewoon uploaden als hij de raster checker errors negeert
