### ISSUE TITLE
[3Di]: Errors in interpolation and visualisation water depths

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#81]
### Contact Details

Stijn O

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=bf3a0fc8-c608-4ad7-99a1-cb3c4507c8f1

### Incident Type

Error

### What priority should we assign to this submission?

Prio1 Very Urgent

### 3Di component

Livesite

### What happened?
In eerste instantie geeft de interpolatiemethode (nearest neigbour) water op plekken waar het eigenlijk droog is. Voornamelijk op plekken met ruwe overgangen in hoogte.

In tweede instantie wordt het probleem verergerd door de visualisatie op de LiveSite. Waterdieptes worden verergerd op het moment van uitzoomen of pannen door verschillende zoomniveaus.

Voor Patrick: Besproken met Jonas en Martijn, hoge prio en moet meteen doorgezet worden. Dit is de info die ik binnen kreeg van Stijn via de servicedesk. Is (nog) beperkt, maar moest snel doorgezet worden.

### How to Reproduce?

https://management.3di.live/schematisations/5109/41429

Demo Oman #0 (kan ook gecheckt worden)

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

[visualisaties_livesite.docx](https://github.com/nens/servicedesk-issue-only/files/9232734/visualisaties_livesite.docx)

### Additional info

Anything else you would like to share?

**Comment by Patrick-Nijman** [comment]
@JJFlorian This is now hotfixed on production. Interpolation looks a bit weird on some levees because it doesn't align smootly with the edge. We think this will be fixed when we release Obstacle Edit. (eta early October)
