### ISSUE TITLE
[3Di]: DWF calculator gives an error if the dry_weather_flow value in v2_imp_surfave table is NULL. 

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#9]
- [ ] https://github.com/nens/ThreeDiToolbox/issues/834

### Contact Details

Bas

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=937a0e8c-74e2-41fa-9768-ac82cdce3b14

### Incident Type

Feedback

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

If the dry_weather_flow value in the v2_imp_surface is set to NULL, the DWF calculator gives a result. 

This makes sense, since the values should be 0 iso NULL. However, Jonas proposed to implement a small check (he mentioned a Try Except check).

### How to Reproduce?

Bas experienced the problem in the Zundert-brp-integraal model

### What did you expect and what was the actual result?

-

### Add screenshots, video's etc

<img width="607" alt="DWF_NULL" src="https://user-images.githubusercontent.com/73856313/144859835-639f7e11-3685-4d3b-bf71-ce425ef07bbe.png">

### Additional info

Anything else you would like to share?

**Comment by lisannewapstra** [comment]
out of date
