### ISSUE TITLE
[3Di]: Add schematisation checker warning for double cumulative discharges

### ISSUE THREAD

**Issue by JJFlorian** [nens/servicedesk-issue-only#91]
- [x] https://github.com/nens/threedi-modelchecker/issues/202

### Contact Details

Leendert

### Topdesk URL (API)

https://nelen-schuurmans.topdesk.net/tas/secure/contained/incident?unid=9a33b7fd-78a0-46a3-b1f9-bf67156ffb9c

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### 3Di component

Modeller Interface (QGIS)

### What happened?

Leendert has the following situation: In the v2_aggregation_settings, he has the following settings:

![image](https://user-images.githubusercontent.com/73856313/186640605-15de8d08-1284-4926-9535-3dbea8557b23.png)

He has 2 cumulative discharge rows (2 & 3), and Martijn S claims that #3 is neglected. The Water Balance tool, however, does not because all aggregations have the same timestep

### How to Reproduce?

management.3di.live/schematisations/5545/40944

### What did you expect and what was the actual result?

Leendert wishs to see a WARNING in the schematisation checker for this situation

**Comment by lisannewapstra** [comment]
done
